// examples/solid-router-simple/src/pages/admin.members.$memberId.tsx
import { useParams } from '@solidjs/router';
import { createResource } from 'solid-js';

import { getMember, sleep } from '~/utils.ts';

export async function loader(memberId: string) {
  await sleep();

  return {
    data: getMember(Number(memberId)),
  };
}

export default function Component() {
  const params = useParams<{ memberId: string }>();

  const [data] = createResource(() => params.memberId, loader);

  return <div>Member: {data()?.data?.name}</div>;
}

// examples/tanstack-router-simple/src/routes/admin.members.$memberId.tsx
import { createFileRoute, notFound } from '@tanstack/react-router';

import { getMember, sleep } from '~/utils.ts';

export const Route = createFileRoute('/admin/members/$memberId')({
  loader: async ({ params: { memberId } }) => {
    await sleep();

    const member = getMember(Number(memberId));
    if (!member) {
      throw notFound();
    }

    return { member };
  },
  component: AdminMember,
  notFoundComponent: NotFound,
});

function AdminMember() {
  const { member } = Route.useLoaderData();

  return <div>Member: {member.name}</div>;
}

function NotFound() {
  return <div>member not found</div>;
}
