// examples/solid-router-simple/src/routes/lazy-component.tsx
import { lazy, Suspense } from 'solid-js';

const MyHeavyComponent = lazy(() => import('~/components/heavy-component.tsx'));

export default function Component() {
  return (
    <div>
      <h2>Lazy Component</h2>

      <p>
        Just a simple component that is lazy loaded. The lazy loaded chunk should only be loaded when this page is
        visited.
      </p>

      <div>
        <Suspense fallback={<div>Loading...</div>}>
          <MyHeavyComponent />
        </Suspense>
      </div>
    </div>
  );
}

// examples/tanstack-router-simple/src/routes/lazy-component.tsx
import { createFileRoute } from '@tanstack/react-router';
import { lazy, Suspense } from 'react';

const MyHeavyComponent = lazy(() => import('~/components/heavy-component.tsx'));

export const Route = createFileRoute('/lazy-component')({
  component: LazyComponent,
  meta: () => [
    {
      title: 'Lazy Component',
    },
  ],
});

function LazyComponent() {
  return (
    <div>
      <h2>Lazy Component</h2>

      <p>
        Just a simple component that is lazy loaded. The lazy loaded chunk should only be loaded when this page is
        visited.
      </p>

      <div className="pt-5">
        <Suspense fallback={<div>Loading heavy component...</div>}>
          <MyHeavyComponent />
        </Suspense>
      </div>
    </div>
  );
}
