// examples/bun-react-router/src/pages/admin.members.$memberId.tsx
import { useLoaderData } from 'react-router-dom';

import { getMember, sleep } from '~/utils.ts';

export async function loader({ params: { memberId } }: any) {
  await sleep();

  return {
    data: getMember(Number(memberId)),
  };
}

export function Component() {
  const { data } = useLoaderData() as Awaited<ReturnType<typeof loader>>;

  if (!data) {
    return <div>member not found</div>;
  }

  return <div>Member: {data.name}</div>;
}

// examples/solid-router-simple/src/routes/admin.members.$memberId.tsx
import { useParams } from '@solidjs/router';
import { createResource, Suspense } from 'solid-js';

import { getMember, sleep } from '~/utils.ts';

export async function loader(memberId: string) {
  await sleep();

  return {
    data: getMember(Number(memberId)),
  };
}

export default function Component() {
  const params = useParams<{ memberId: string }>();

  const [data] = createResource(() => params.memberId, loader);

  return (
    <Suspense fallback="Loading...">
      <div>Member: {data()?.data?.name}</div>
    </Suspense>
  );
}
