// packages/vite/src/__fixtures__/lazy-route-tree/routes.tsx
import './routes.css';

import { Component as RootLayout } from './pages/root.tsx';

export const routes = [
  {
    path: '/',
    element: <RootLayout />,
    children: [
      {
        index: true,
        lazy: () => import('./pages/_index.tsx'),
      },
      {
        path: 'lazy-component',
        lazy: () => import('./pages/lazy-component.tsx'),
      },
      {
        path: 'admin',
        lazy: () => import('./pages/admin.tsx'),
        children: [
          {
            index: true,
            lazy: () => import('./pages/admin._index.tsx'),
          },
          {
            path: 'members',
            lazy: () => import('./pages/admin.members.tsx'),
            children: [
              {
                index: true,
                lazy: () => import('./pages/admin.members._index.tsx'),
              },
              {
                path: ':memberId',
                lazy: () => import('./pages/admin.members.$memberId.tsx'),
              },
            ],
          },
        ],
      },
    ],
  },
];

// examples/solid-router-simple/src/routes.tsx
import type { RouteDefinition } from '@solidjs/router';
import { lazy } from 'solid-js';

import { Component as RootLayout } from './pages/root.tsx';

export const routes: RouteDefinition = {
  path: '/',
  element: RootLayout,
  children: [
    {
      path: '/',
      component: lazy(() => import('~/pages/_index.tsx')),
    },

    {
      path: 'lazy-component',
      component: lazy(() => import('~/pages/lazy-component.tsx')),
    },

    {
      path: 'admin',
      component: lazy(() => import('~/pages/admin.tsx')),
      children: [
        {
          path: '',
          component: lazy(() => import('~/pages/admin._index.tsx')),
        },

        {
          path: 'members',
          component: lazy(() => import('~/pages/admin.members.tsx')),
          children: [
            {
              path: '',
              component: lazy(() => import('~/pages/admin.members._index.tsx')),
            },

            {
              path: ':memberId',
              component: lazy(() => import('~/pages/admin.members.$memberId.tsx')),
            },
          ],
        },
      ],
    },
  ],
};
