// examples/react-router-simple/src/routes/admin.tsx
import './admin.css';

import { useCallback } from 'react';
import { NavLink, Outlet } from 'react-router-dom';

export function Component() {
  const linkClass = useCallback(({ isActive }: any) => `admin-nav__item ${isActive ? 'active' : undefined}`, []);

  return (
    <>
      <h2>Admin Area</h2>

      <nav className="admin-nav">
        <NavLink to="" className={linkClass} end>
          Home
        </NavLink>

        <NavLink to="members" className={linkClass}>
          Members
        </NavLink>
      </nav>

      <div className="admin-content">
        <Outlet />
      </div>
    </>
  );
}

// examples/solid-router-simple/src/pages/admin.tsx
import './admin.css';

import { A } from '@solidjs/router';
import type { ParentProps } from 'solid-js';

export default function Component(props: ParentProps) {
  return (
    <>
      <h2>Admin Area</h2>

      <nav class="admin-nav">
        <A href="" class="admin-nav__item" activeClass="active" end>
          Home
        </A>

        <A href="members" class="admin-nav__item" activeClass="active">
          Members
        </A>
      </nav>

      <div class="admin-content">{props.children}</div>
    </>
  );
}
